name: Build and Upload Artifacts

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python -m unittest discover -s tests

      - name: Package Application
        run: |
          mkdir -p build
          cp -r src build/
          tar -czf my_python_app.tar.gz build/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: my_python_app
          path: my_python_app.tar.gz
